{% set name = "ptac" %}
{% set version = "0.1.2a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ptac-{{ version }}.tar.gz
  sha256: 86da137e9b23241f42540ea5bb6d3c774b75f8f52650bce549d8497bce34a6df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip

  build:
    - python >=3.8
    - setuptools
 
  run:
    - python >=3.8
    - osmnx==1.1.1
    - networkx>=2.5
    - numpy==1.22.4
    - Shapely==1.7.1
    - pyproj==3.1.0
    - geopandas==0.9.0
    - rasterio==1.2.4
    - pandas==1.2.4

test:
  imports:
    - ptac
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DLR-VF/PtAC
  license: Eclipse Public License
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - serrayos
    - SimonNieland
