package:
  name: ptac
  version: 0.1.1a

source:
  path: .
  # git-url: https://github.com/DLR-VF/PtAC

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - osmnx==1.1.1
    - networkx>=2.5
    - numpy==1.22.4
    - Shapely==1.7.1
    - pyproj==3.1.0
    - geopandas==0.9.0
    - rasterio==1.2.4
    - pandas==1.2.4

test:
  source_files:
    - tests/test_ptac.py

about:
  home: https://github.com/DLR-VF/PtAC
  license: Eclipse Public License
