name: ptac-dev

channels:
  #- conda-forge
  - defaults

dependencies:
    # required
    # - python=3.8
    - osmnx
    - networkx #>=2.5
    - numpy #>=1.20.3
    - pandas #==1.2.4
    - Shapely #==1.7.1
    - pyproj #==3.1.0
    - geopandas
    - setuptools

    # extras
    - folium
    - gdal
    - rasterio
    - scikit-learn
    - scipy

    # linting/testing
    - pylint
    - coverage
    - flake8
    - isort
    - pydocstyle
    - pytest
    - sphinx
    - sphinx_rtd_theme
