package:
  name: ptac
  version: "0.1.1a"

requirements:
  build:
    - python={{ python_version }}

  run:
    - python={{ python_version }}

source:
  path: ../setup.py

build:
  script: python setup.py install # --single-version-externally-managed --record=record.txt
  string: py{{ python_version | replace(".", "") }}

