name: ptac-dev

channels:
  - conda-forge
  - defaults

dependencies:
    # required
    - osmnx
    - geopandas
    - networkx
    - numpy
    - pandas
    - pyproj
    - rasterio
    - Shapely


    # extras
    # - folium
    # - gdal
    # - rasterio
    # - scikit-learn
    # - scipy
    - black=22.*
    - pylint
    - coverage
    - flake8
    - flake8-bugbear
    - isort
    - pydocstyle
    - pytest
    - sphinx
