name: Test PtAC with Mamba in Linux

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ continuous-integration ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            environment-file: environment.yml
            miniforge-variant: Mambaforge
            miniforge-version: 4.9.2-4

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup conda environment with mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          activate-environment: ptac-dev
          python-version: ${{ matrix.python-version }}
          condarc-file: ${{ matrix.condarc-file }}
          environment-file: ${{ matrix.environment-file }}
          miniforge-variant: ${{ matrix.miniforge-variant }}
          miniforge-version: ${{ matrix.miniforge-version }}

      - name: Install PtAC
        run: |
          python setup.py install
          conda list
          conda info --all

      - name: Lint code
        shell: bash -l {0}
        run: |
          # conda install flake8
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test code
        shell: bash -l {0}
        run: |
          pytest -v
