# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: CI Pipeline for PtAC

on:
  push:
    branches: [ continuous-integration ]
  pull_request:
    branches: [ continuous-integration ]

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.8
          - 3.9
          - '3.10'
          - pypy3
        exclude:
          # PYPY on Windows is painfully slow, if not broken
          - platform: windows-latest
            python-version: pypy3 
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./
      - run: poetry self --version
